name: PHPStan Action
description: Lint your PHP code with PHPStan
author: Pieter Maene
branding:
  icon: shield
  color: yellow

inputs:
  github-token:
    description: The installation access token for the job
    default: ${{ github.token }}
    required: true

runs:
  using: docker
  image: Dockerfile
  env:
    GITHUB_TOKEN: ${{ inputs.github-token }}
