name: Go

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Run GolangCI-Lint
        uses: golangci/golangci-lint-action@v2.5.2
